export const FIELD_COMMAND_COMPLETENESS_METHOD_NAME = 'completenessMethod'
export const FIELD_COMMAND_DEFAULT_MESSAGE_NAME = 'defaultMessage'
export const FIELD_COMMAND_ID_NAME = 'id'
export const FIELD_COMMAND_MORE_THAN_ONE_ORG_UNIT_MESSAGE_NAME =
    'moreThanOneOrgUnitMessage'
export const FIELD_COMMAND_NAME_NAME = 'name'
export const FIELD_COMMAND_NO_USER_MESSAGE_NAME = 'noUserMessage'
export const FIELD_COMMAND_PARSER_NAME = 'parserType'
export const FIELD_COMMAND_PROGAM_NAME = 'program'
export const FIELD_COMMAND_PROGAM_STAGE_NAME = 'programStage'
export const FIELD_COMMAND_SEPARATOR_NAME = 'separator'
export const FIELD_COMMAND_SMS_CODES_NAME = 'smsCodes'
export const FIELD_COMMAND_SPECIAL_CHARS_NAME = 'specialCharacters'
export const FIELD_COMMAND_SUCCESS_MESSAGE_NAME = 'successMessage'
export const FIELD_COMMAND_USE_CURRENT_PERIOD_FOR_REPORTING_NAME =
    'currentPeriodUsedForReporting'
export const FIELD_COMMAND_WRONG_FORMAT_MESSAGE_NAME = 'wrongFormatMessage'
export const FIELD_COMMAND_CONFIRM_MESSAGE_NAME = 'receivedMessage'
