const PROGRAMS_WITH_REGISTRATION = 'PROGRAMS_WITH_REGISTRATION'
const PROGRAMS_WITHOUT_REGISTRATION = 'PROGRAMS_WITHOUT_REGISTRATION'
const ALL_PROGRAMS = 'ALL_PROGRAMS'

export const programTypes = {
    PROGRAMS_WITH_REGISTRATION,
    PROGRAMS_WITHOUT_REGISTRATION,
    ALL_PROGRAMS,
}
