const data = {
    pager: { page: 1, pageCount: 10, total: 100, pageSize: 10 },
    messages: [
        {
            translations: [],
            externalAccess: false,
            userGroupAccesses: [],
            userAccesses: [],
            favorites: [],
            favorite: false,
            attributeValues: [],
            sender: 'DHIS-System',
            recipients: ['083 886 2694'],
            date: '2014-03-31T00:00:00.349',
            message:
                'Dear {patient-name}. You missed your TB visit appointment. Please come to the clinic as soon as possible,\r\nThank you.',
            status: 'OUTBOUND',
            messageId: 1452008,
        },
        {
            translations: [],
            externalAccess: false,
            userGroupAccesses: [],
            userAccesses: [],
            favorites: [],
            favorite: false,
            attributeValues: [],
            sender: 'DHIS-System',
            recipients: ['084 156 7600'],
            date: '2014-03-31T00:00:00.358',
            message:
                'Dear {patient-name}. You missed your TB visit appointment. Please come to the clinic as soon as possible,\r\nThank you.',
            status: 'OUTBOUND',
            messageId: 1452009,
        },
        {
            translations: [],
            externalAccess: false,
            userGroupAccesses: [],
            userAccesses: [],
            favorites: [],
            favorite: false,
            attributeValues: [],
            sender: 'DHIS-System',
            recipients: ['082 775 1953'],
            date: '2014-03-31T00:00:00.367',
            message:
                'Dear {patient-name}. You missed your TB visit appointment. Please come to the clinic as soon as possible,\r\nThank you.',
            status: 'OUTBOUND',
            messageId: 1452010,
        },
        {
            translations: [],
            externalAccess: false,
            userGroupAccesses: [],
            userAccesses: [],
            favorites: [],
            favorite: false,
            attributeValues: [],
            sender: 'DHIS-System',
            recipients: ['082 587 4711'],
            date: '2014-03-31T00:00:00.378',
            message:
                'Dear {patient-name}. You missed your TB visit appointment. Please come to the clinic as soon as possible,\r\nThank you.',
            status: 'OUTBOUND',
            messageId: 1452011,
        },
        {
            translations: [],
            externalAccess: false,
            userGroupAccesses: [],
            userAccesses: [],
            favorites: [],
            favorite: false,
            attributeValues: [],
            sender: 'DHIS-System',
            recipients: ['085 462 2193'],
            date: '2014-03-31T00:00:00.388',
            message:
                'Dear {patient-name}. You missed your TB visit appointment. Please come to the clinic as soon as possible,\r\nThank you.',
            status: 'OUTBOUND',
            messageId: 1452012,
        },
        {
            translations: [],
            externalAccess: false,
            userGroupAccesses: [],
            userAccesses: [],
            favorites: [],
            favorite: false,
            attributeValues: [],
            sender: 'DHIS-System',
            recipients: ['084 825 7107'],
            date: '2014-03-31T00:00:00.397',
            message:
                'Dear {patient-name}. You missed your TB visit appointment. Please come to the clinic as soon as possible,\r\nThank you.',
            status: 'OUTBOUND',
            messageId: 1452013,
        },
        {
            translations: [],
            externalAccess: false,
            userGroupAccesses: [],
            userAccesses: [],
            favorites: [],
            favorite: false,
            attributeValues: [],
            sender: 'DHIS-System',
            recipients: ['082 279 5826'],
            date: '2014-03-31T00:00:00.406',
            message:
                'Dear {patient-name}. You missed your TB visit appointment. Please come to the clinic as soon as possible,\r\nThank you.',
            status: 'OUTBOUND',
            messageId: 1452014,
        },
        {
            translations: [],
            externalAccess: false,
            userGroupAccesses: [],
            userAccesses: [],
            favorites: [],
            favorite: false,
            attributeValues: [],
            sender: 'DHIS-System',
            recipients: ['083 618 2510'],
            date: '2014-03-31T00:00:00.414',
            message:
                'Dear {patient-name}. You missed your TB visit appointment. Please come to the clinic as soon as possible,\r\nThank you.',
            status: 'OUTBOUND',
            messageId: 1452015,
        },
        {
            translations: [],
            externalAccess: false,
            userGroupAccesses: [],
            userAccesses: [],
            favorites: [],
            favorite: false,
            attributeValues: [],
            sender: 'DHIS-System',
            recipients: ['083 766 8064'],
            date: '2014-03-31T00:00:00.423',
            message:
                'Dear {patient-name}. You missed your TB visit appointment. Please come to the clinic as soon as possible,\r\nThank you.',
            status: 'OUTBOUND',
            messageId: 1452016,
        },
        {
            translations: [],
            externalAccess: false,
            userGroupAccesses: [],
            userAccesses: [],
            favorites: [],
            favorite: false,
            attributeValues: [],
            sender: 'DHIS-System',
            recipients: ['083 178 2682'],
            date: '2014-03-31T00:00:00.432',
            message:
                'Dear {patient-name}. You missed your TB visit appointment. Please come to the clinic as soon as possible,\r\nThank you.',
            status: 'OUTBOUND',
            messageId: 1452017,
        },
        {
            translations: [],
            externalAccess: false,
            userGroupAccesses: [],
            userAccesses: [],
            favorites: [],
            favorite: false,
            attributeValues: [],
            sender: 'DHIS-System',
            recipients: ['082 148 6715'],
            date: '2014-03-31T00:00:00.442',
            message:
                'Dear {patient-name}. You missed your TB visit appointment. Please come to the clinic as soon as possible,\r\nThank you.',
            status: 'OUTBOUND',
            messageId: 1452018,
        },
        {
            translations: [],
            externalAccess: false,
            userGroupAccesses: [],
            userAccesses: [],
            favorites: [],
            favorite: false,
            attributeValues: [],
            recipients: ['004797033786'],
            date: '2016-04-21T17:39:09.481',
            message: 'Hey',
            status: 'ERROR',
            messageId: 858802,
        },
        {
            translations: [],
            externalAccess: false,
            userGroupAccesses: [],
            userAccesses: [],
            favorites: [],
            favorite: false,
            attributeValues: [],
            recipients: ['+4797033786'],
            date: '2016-04-21T17:52:25.868',
            message: 'Hey from DHIS 2 Tracker',
            status: 'SENT',
            messageId: 858805,
        },
    ],
}

export default data
